import MainLayout from "@/components/GlobalComponents";
import Loading from "./loading";
import { Suspense } from "react";

export const metadata = {
  title: "FooFest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <MainLayout page="booking">
      <Suspense fallback={<Loading />}>{children}</Suspense>
    </MainLayout>
  );
}
