import MainLayout from "@/components/GlobalComponents";

export const metadata = {
  title: "FooFest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <MainLayout page="booking">{children}</MainLayout>;
}
